on: [push, pull_request]
name: Test
jobs:
  test:
    steps:
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.75.0
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: cd fly-ruby && rake
