on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }} with options - ${{ toJson(matrix.options) }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, ruby_version: 2.7 }
          - { os: ubuntu-latest, ruby_version: '3.0' }
          - { os: ubuntu-latest, ruby_version: 3.1 }
    services:
    # label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # service environment variables
        # `POSTGRES_HOST` is `postgres`
        env:
          # optional (defaults to `postgres`)
          POSTGRES_DB: fly_ruby_test
          # required
          POSTGRES_PASSWORD: postgres_password
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: postgres_user
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1
      with:
        bundler: 1
        ruby-version: ${{ matrix.ruby_version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      env:
        DATABASE_USER: postgres_user
      run: |
        bundle install --jobs 4 --retry 3
        rake
